from django.db import migrations
from api.models import Stock


def stocks_bulky_insertion(apps, schema_editor):
    stocks = [
        {
            "company_name": "Ammu Nation",
            "description": "Arming Your Future",
            "industry": "GUNS",
            "abbreviation": "AMU",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "AeroFit",
            "description": "Elevate Your Game, Reach New Heights",
            "industry": "SPORTING_GOODS",
            "abbreviation": "ARF",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Augury Insurance",
            "description": "Shielding Your Tomorrow, Today",
            "industry": "INSURANCE",
            "abbreviation": "AUG",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Cool Beans",
            "description": "Cool Moments, Warm Memories",
            "industry": "FRANCHISE",
            "abbreviation": "BAN",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Badger",
            "description": "Connecting Beyond Boundaries",
            "industry": "TELECOM",
            "abbreviation": "BDG",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Bean Machine",
            "description": "Fueling Your Day, One Sip at a Time",
            "industry": "FRANCHISE",
            "abbreviation": "BEN",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Betta Pharmaceuticals",
            "description": "Better Health, Better Life",
            "industry": "PHARMA",
            "abbreviation": "BET",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Bürgerfahrzeug",
            "description": "Driving Dreams, Building Futures",
            "industry": "AUTOMOTIVE",
            "abbreviation": "BFA",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Burget Shot",
            "description": "Bite into Flavor, Taste the Adventure",
            "industry": "FOODS",
            "abbreviation": "BGR",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Bilkinton",
            "description": "Innovating Health, Enriching Lives",
            "industry": "PHARMA",
            "abbreviation": "BIK",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Bank of Liberty",
            "description": "Empowering Dreams, Enriching Futures",
            "industry": "FINANCES",
            "abbreviation": "BIL",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Binco",
            "description": "Fashion for Every Journey",
            "industry": "FRANCHISE",
            "abbreviation": "BIN",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Bleeter",
            "description": "Share Your World, One Bleet at a Time",
            "industry": "SOCIAL_MEDIA",
            "abbreviation": "BLE",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Bob Muiét",
            "description": "Every Flavor, a Story Untold",
            "industry": "FRANCHISE",
            "abbreviation": "BOM",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Brute",
            "description": "Power and Precision in Motion",
            "industry": "AUTOMOTIVE",
            "abbreviation": "BRU",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Bitter Sweet",
            "description": "Taste the Joy of Connection",
            "industry": "TELECOM",
            "abbreviation": "BTR",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Bullhead",
            "description": "Defending Justice, Safeguarding Truth",
            "industry": "LAW",
            "abbreviation": "BUL",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Cluckin Bell",
            "description": "A Flavorful Tradition, Every Bell Satisfies",
            "industry": "FOODS",
            "abbreviation": "CLK",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "CNT",
            "description": "Bringing Life to the Screen",
            "industry": "TELEVISON",
            "abbreviation": "CNT",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Crevis",
            "description": "Crafting Memories, One Creation at a Time",
            "industry": "FRANCHISE",
            "abbreviation": "CRE",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Debonaire",
            "description": "Elegance in Every Puff, Luxury in Every Draw",
            "industry": "TOBACCO",
            "abbreviation": "DEB",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Daily Globe",
            "description": "Every Story, Every Perspective",
            "industry": "JOURNALISTIC",
            "abbreviation": "DGP",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Dollar Pills",
            "description": "Your Health, Our Priority",
            "industry": "PHARMA",
            "abbreviation": "DOP",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "DynaSport Gear",
            "description": "Gear Up for Greatness, Play with Passion",
            "industry": "SPORTING_GOODS",
            "abbreviation": "DYG",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "eCola",
            "description": "Quenching Thirsts, Fueling Moments",
            "industry": "DRINKS",
            "abbreviation": "ECL",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Electra Motion",
            "description": "Electrifying the Road Ahead",
            "industry": "AUTOMOTIVE",
            "abbreviation": "ELM",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Air Emu",
            "description": "Wings of Adventure, Skies of Discovery",
            "industry": "AIRLINE",
            "abbreviation": "EMU",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Eyefind",
            "description": "See the World through Innovation",
            "industry": "TECHONOLOGY",
            "abbreviation": "EYE",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Facade",
            "description": "Show Your True Face to the World",
            "industry": "SOCIAL_MEDIA",
            "abbreviation": "FAC",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "FLEECA Banks",
            "description": "Your Wealth, Our Expertise",
            "industry": "FINANCES",
            "abbreviation": "FLC",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Fruit",
            "description": "Juicy Conversations, Sweet Connections",
            "industry": "TELECOM",
            "abbreviation": "FRT",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Fly US",
            "description": "Taking You Beyond, Above and Beyond",
            "industry": "AIRLINE",
            "abbreviation": "FUS",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Gastro Band",
            "description": "Taste, Share, Connect",
            "industry": "SOCIAL_MEDIA",
            "abbreviation": "GAS",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Goal Coast Developmets",
            "description": "Building Dreams, Shaping Horizons",
            "industry": "REAL_STATE",
            "abbreviation": "GCD",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "GoPostal",
            "description": "Delivering Smiles, Connecting Miles",
            "industry": "TRANSPORT",
            "abbreviation": "GOP",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Grain of Truth",
            "description": "Savor the Truth in Every Bite",
            "industry": "FOODS",
            "abbreviation": "GOT",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Gruppe Sechs",
            "description": "Guardians of Trust, Protectors of Tomorrow",
            "industry": "SECURITY",
            "abbreviation": "GRU",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Hammerstein & Faust",
            "description": "Pounding for Justice, Crafting Solutions",
            "industry": "LAW",
            "abbreviation": "HAF",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Hawk & Little",
            "description": "Might in Every Shot, Strength in Every Trigger",
            "industry": "GUNS",
            "abbreviation": "HAL",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Hijak",
            "description": "Journey Beyond Boundaries, Ride the Hijak Way",
            "industry": "AUTOMOTIVE",
            "abbreviation": "HJK",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Horizon Haven",
            "description": "Your Horizon, Your Home",
            "industry": "REAL_STATE",
            "abbreviation": "HOH",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "HVY",
            "description": "Built Tough, Ready for Anything",
            "industry": "AUTOMOTIVE",
            "abbreviation": "HVY",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Krapea",
            "description": "Taste Crafted, Comfort Perfected",
            "industry": "FRANCHISE",
            "abbreviation": "KRP",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Life Invader",
            "description": "Connecting Lives, Shaping Stories",
            "industry": "SOCIAL_MEDIA",
            "abbreviation": "LFI",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Los Santos Customs",
            "description": "Turning Rides into Reflections of You",
            "industry": "AUTOMOTIVE",
            "abbreviation": "LSC",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Los Santos Transit",
            "description": "Moving Dreams Forward, Together",
            "industry": "TRANSPORT",
            "abbreviation": "LST",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "LTD",
            "description": "Fueling Journeys, Empowering Destinations",
            "industry": "FUEL_DISTRIBUTION",
            "abbreviation": "LTD",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Maibatsu",
            "description": "Driving Innovation, Defining the Future",
            "industry": "AUTOMOTIVE",
            "abbreviation": "MAI",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Maze Bank",
            "description": "Building Bridges to Your Financial Future",
            "industry": "FINANCES",
            "abbreviation": "MAZ",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Merryweather",
            "description": "Defending with Honor, Securing with Valor",
            "industry": "SECURITY",
            "abbreviation": "MER",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Mors Mutual Insurance",
            "description": "Protection Beyond Expectations",
            "industry": "INSURANCE",
            "abbreviation": "MOR",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "MysticData Systems",
            "description": "Unraveling the Future, Byte by Byte",
            "industry": "TECHONOLOGY",
            "abbreviation": "MYS",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "NeuralNex Technologies",
            "description": "Connecting Minds, Unleashing Tomorrow",
            "industry": "TECHONOLOGY",
            "abbreviation": "NNX",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Pisbwasser",
            "description": "Refreshing the Spirit of Life",
            "industry": "DRINKS",
            "abbreviation": "PIS",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Pump & Run Gymnasium",
            "description": "Pump Up, Conquer All",
            "industry": "FRANCHISE",
            "abbreviation": "PMP",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Ponsonbys",
            "description": "Elegance Beyond Measure",
            "industry": "FRANCHISE",
            "abbreviation": "PON",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Post Op",
            "description": "Delivering Dreams, Connecting Destinations",
            "industry": "TRANSPORT",
            "abbreviation": "POP",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Prolaps",
            "description": "Elevate Your Style, Own Your Fashion",
            "industry": "FRANCHISE",
            "abbreviation": "PRO",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "River Cloud Tech",
            "description": "Navigating Boundaries, Innovating Tomorrows",
            "industry": "TECHONOLOGY",
            "abbreviation": "RCT",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "RadiantTunes",
            "description": "Music that Illuminates, Tunes that Resonate",
            "industry": "RADIO",
            "abbreviation": "RDT",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Richards Majestic",
            "description": "Dramas That Define, Stories That Shine",
            "industry": "TELEVISON",
            "abbreviation": "RIM",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Radio Los Santos",
            "description": "Tune In, Turn Up Your Life",
            "industry": "RADIO",
            "abbreviation": "RLS",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Ron Oil",
            "description": "Fuelling Progress, Powering Potential",
            "industry": "FUEL_DISTRIBUTION",
            "abbreviation": "RON",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Redwood",
            "description": "Rich Flavor, Timeless Pleasure",
            "industry": "TOBACCO",
            "abbreviation": "RWC",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Shark",
            "description": "Charting Courses to Financial Success",
            "industry": "FINANCES",
            "abbreviation": "SHK",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Shrewsbury",
            "description": "Precision in Every Shot, Quality in Every Mark",
            "industry": "GUNS",
            "abbreviation": "SHR",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Schyster",
            "description": "Performance Refined, Excellence Redefined",
            "industry": "AUTOMOTIVE",
            "abbreviation": "SHT",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "SkySultan Airlines",
            "description": "Soaring Skies, Unforgettable Journeys",
            "industry": "AIRLINE",
            "abbreviation": "SKS",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Sprunk",
            "description": "Fizzing Joy in Every Sip",
            "industry": "DRINKS",
            "abbreviation": "SPU",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Suburban",
            "description": "Style that Resonates, Fashion for All",
            "industry": "FRANCHISE",
            "abbreviation": "SUB",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Taco Bomb",
            "description": "Explosion of Flavors, A Bomb of Taste",
            "industry": "FOODS",
            "abbreviation": "TBO",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Ubermacht",
            "description": "Crafting Superiority, Driving Excellence",
            "industry": "AUTOMOTIVE",
            "abbreviation": "UMA",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "UrbanInk Media Group",
            "description": "Inking Truths, Shaping Perspectives",
            "industry": "JOURNALISTIC",
            "abbreviation": "UMG",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Vanilla Unicorn",
            "description": "Unleash Your Fantasies, Tune into Desire",
            "industry": "TELEVISON",
            "abbreviation": "UNI",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Up-n-Atom Burger",
            "description": "Bite into Bliss, Taste the Explosion",
            "industry": "FOODS",
            "abbreviation": "UPA",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Vapid",
            "description": "Unleash the Road within You",
            "industry": "AUTOMOTIVE",
            "abbreviation": "VAP",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Vibe Loop",
            "description": "Weaving Connections, Sharing Waves",
            "industry": "SOCIAL_MEDIA",
            "abbreviation": "VLP",
            "stock_market": "DUNEMI",
        },
        {
            "company_name": "Whiz",
            "description": "Connecting Moments, Amplifying Lives",
            "industry": "TELECOM",
            "abbreviation": "WIZ",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Weazel",
            "description": "See Beyond, Tune into Tomorrow",
            "industry": "TELEVISON",
            "abbreviation": "WZL",
            "stock_market": "DASDAQ",
        },
        {
            "company_name": "Zip",
            "description": "Unzip Your Imagination, Unleash the Experience",
            "industry": "FRANCHISE",
            "abbreviation": "ZIT",
            "stock_market": "DASDAQ",
        },
    ]

    for stock in stocks:
        Stock.objects.create(**stock)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_auto_20230814_2343"),
    ]

    operations = [
        migrations.RunPython(
            stocks_bulky_insertion,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
