# Generated by Django 3.2.16 on 2023-08-14 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('abbreviation', models.CharField(max_length=3)),
                ('industry', models.CharField(choices=[('GUNS', 'Guns'), ('SPORTING_GOODS', 'Sporting Goods'), ('INSURANCE', 'Insurance'), ('FRANCHISE', 'Franchise'), ('TELECOM', 'Telecom'), ('PHARMA', 'Pharma'), ('AUTOMOTIVE', 'Automotive'), ('FOODS', 'Foods'), ('FINANCES', 'Finances'), ('SOCIAL_MEDIA', 'Social Media'), ('LAW', 'Law'), ('TELEVISON', 'Televison'), ('TOBACCO', 'Tobacco'), ('JOURNALISTIC', 'Journalistic'), ('DRINKS', 'Drinks'), ('AIRLINE', 'Airline'), ('TECHONOLOGY', 'Techonology'), ('REAL_ESTATE', 'Real Estate'), ('TRANSPORT', 'Transport'), ('SECURITY', 'Security'), ('FUEL_DISTRIBUTION', 'Fuel Distribution'), ('RADIO', 'Radio')], max_length=128)),
                ('stock_market', models.CharField(choices=[('DASDAQ', 'DASDAQ'), ('DUNEMI', 'DASDAQ')], max_length=128)),
                ('logo_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
