# Generated by Django 3.2.16 on 2023-09-17 17:47

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('ceo_name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('industry', models.CharField(choices=[('GUNS', 'Guns'), ('SPORTING_GOODS', 'Sporting Goods'), ('INSURANCE', 'Insurance'), ('FRANCHISE', 'Franchise'), ('TELECOM', 'Telecom'), ('PHARMA', 'Pharma'), ('AUTOMOTIVE', 'Automotive'), ('FOODS', 'Foods'), ('FINANCES', 'Finances'), ('SOCIAL_MEDIA', 'Social Media'), ('LAW', 'Law'), ('TELEVISON', 'Televison'), ('TOBACCO', 'Tobacco'), ('JOURNALISTIC', 'Journalistic'), ('DRINKS', 'Drinks'), ('AIRLINE', 'Airline'), ('TECHONOLOGY', 'Techonology'), ('REAL_ESTATE', 'Real Estate'), ('TRANSPORT', 'Transport'), ('SECURITY', 'Security'), ('FUEL_DISTRIBUTION', 'Fuel Distribution'), ('RADIO', 'Radio')], max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=128)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.BigIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stock')),
            ],
            options={
                'verbose_name_plural': 'Price Movements',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
    ]
