# Generated by Django 3.2.16 on 2023-08-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_market',
            field=models.CharField(choices=[('DASDAQ', 'DASDAQ'), ('DUNEMI', 'DUNEMI')], max_length=128),
        ),
    ]
