# Generated by Django 3.2.16 on 2023-08-14 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230814_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='PriceMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('movement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
