# Generated by Django 3.2.16 on 2023-09-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230904_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
