# Generated by Django 3.2.16 on 2023-08-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_users_insertion'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
